/*
Copyright 2014-2015 Intecs Spa

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/


package eu.betaas.apps.lib.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-10-13T16:50:23.460+02:00
 * Generated source version: 2.7.6
 * 
 */
public final class ServiceManagerExternalIFPortType_ServiceManagerExternalIFPort_Client {

    private static final QName SERVICE_NAME = new QName("http://api.servicemanager.service.betaas.eu/", "ServiceManagerExternalIF");

    private ServiceManagerExternalIFPortType_ServiceManagerExternalIFPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceManagerExternalIF.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServiceManagerExternalIF ss = new ServiceManagerExternalIF(wsdlURL, SERVICE_NAME);
        ServiceManagerExternalIFPortType port = ss.getServiceManagerExternalIFPort();  
        
        {
        System.out.println("Invoking setThingServiceData...");
        java.lang.String _setThingServiceData_arg0 = "";
        java.lang.String _setThingServiceData_arg1 = "";
        java.lang.String _setThingServiceData_arg2 = "";
        java.lang.String _setThingServiceData_arg3 = "";
        boolean _setThingServiceData__return = port.setThingServiceData(_setThingServiceData_arg0, _setThingServiceData_arg1, _setThingServiceData_arg2, _setThingServiceData_arg3);
        System.out.println("setThingServiceData.result=" + _setThingServiceData__return);


        }
        {
        System.out.println("Invoking unregister...");
        java.lang.String _unregister_arg0 = "";
        java.lang.String _unregister_arg1 = "";
        java.lang.String _unregister_arg2 = "";
        boolean _unregister__return = port.unregister(_unregister_arg0, _unregister_arg1, _unregister_arg2);
        System.out.println("unregister.result=" + _unregister__return);


        }
        {
        System.out.println("Invoking getExtendedServiceData...");
        java.lang.String _getExtendedServiceData_arg0 = "";
        java.lang.String _getExtendedServiceData_arg1 = "";
        java.lang.String _getExtendedServiceData_arg2 = "";
        java.lang.String _getExtendedServiceData__return = port.getExtendedServiceData(_getExtendedServiceData_arg0, _getExtendedServiceData_arg1, _getExtendedServiceData_arg2);
        System.out.println("getExtendedServiceData.result=" + _getExtendedServiceData__return);


        }
        {
        System.out.println("Invoking uninstallApplication...");
        java.lang.String _uninstallApplication_arg0 = "";
        java.lang.String _uninstallApplication_arg1 = "";
        boolean _uninstallApplication__return = port.uninstallApplication(_uninstallApplication_arg0, _uninstallApplication_arg1);
        System.out.println("uninstallApplication.result=" + _uninstallApplication__return);


        }
        {
        System.out.println("Invoking register...");
        java.lang.String _register_arg0 = "";
        java.lang.String _register_arg1 = "";
        java.lang.String _register_arg2 = "";
        boolean _register__return = port.register(_register_arg0, _register_arg1, _register_arg2);
        System.out.println("register.result=" + _register__return);


        }
        {
        System.out.println("Invoking getTaskData...");
        java.lang.String _getTaskData_arg0 = "";
        java.lang.String _getTaskData_arg1 = "";
        java.lang.String _getTaskData__return = port.getTaskData(_getTaskData_arg0, _getTaskData_arg1);
        System.out.println("getTaskData.result=" + _getTaskData__return);


        }
        {
        System.out.println("Invoking installApplication...");
        java.lang.String _installApplication_arg0 = "";
        java.lang.String _installApplication__return = port.installApplication(_installApplication_arg0);
        System.out.println("installApplication.result=" + _installApplication__return);


        }
        {
        System.out.println("Invoking getApplicationServices...");
        java.lang.String _getApplicationServices_arg0 = "";
        java.lang.String _getApplicationServices__return = port.getApplicationServices(_getApplicationServices_arg0);
        System.out.println("getApplicationServices.result=" + _getApplicationServices__return);


        }
        {
        System.out.println("Invoking getGWId...");
        java.lang.String _getGWId__return = port.getGWId();
        System.out.println("getGWId.result=" + _getGWId__return);


        }
        {
        System.out.println("Invoking getThingServiceData...");
        java.lang.String _getThingServiceData_arg0 = "";
        java.lang.String _getThingServiceData_arg1 = "";
        java.lang.String _getThingServiceData_arg2 = "";
        java.lang.String _getThingServiceData__return = port.getThingServiceData(_getThingServiceData_arg0, _getThingServiceData_arg1, _getThingServiceData_arg2);
        System.out.println("getThingServiceData.result=" + _getThingServiceData__return);


        }

        System.exit(0);
    }

}
