/*
Copyright 2014-2015 Intecs Spa

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

package eu.betaas.apps.lib.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-10-13T16:50:23.675+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://api.servicemanager.service.betaas.eu/", name = "ServiceManagerExternalIFPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceManagerExternalIFPortType {

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "setThingServiceData", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.SetThingServiceData")
    @WebMethod
    @ResponseWrapper(localName = "setThingServiceDataResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.SetThingServiceDataResponse")
    public boolean setThingServiceData(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "unregister", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.Unregister")
    @WebMethod
    @ResponseWrapper(localName = "unregisterResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.UnregisterResponse")
    public boolean unregister(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "getExtendedServiceData", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetExtendedServiceData")
    @WebMethod
    @ResponseWrapper(localName = "getExtendedServiceDataResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetExtendedServiceDataResponse")
    public java.lang.String getExtendedServiceData(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "uninstallApplication", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.UninstallApplication")
    @WebMethod
    @ResponseWrapper(localName = "uninstallApplicationResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.UninstallApplicationResponse")
    public boolean uninstallApplication(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "register", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.Register")
    @WebMethod
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.RegisterResponse")
    public boolean register(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "getTaskData", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetTaskData")
    @WebMethod
    @ResponseWrapper(localName = "getTaskDataResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetTaskDataResponse")
    public java.lang.String getTaskData(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "installApplication", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.InstallApplication")
    @WebMethod
    @ResponseWrapper(localName = "installApplicationResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.InstallApplicationResponse")
    public java.lang.String installApplication(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "getApplicationServices", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetApplicationServices")
    @WebMethod
    @ResponseWrapper(localName = "getApplicationServicesResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetApplicationServicesResponse")
    public java.lang.String getApplicationServices(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "getGWId", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetGWId")
    @WebMethod
    @ResponseWrapper(localName = "getGWIdResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetGWIdResponse")
    public java.lang.String getGWId();

    @WebResult(name = "return", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
    @RequestWrapper(localName = "getThingServiceData", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetThingServiceData")
    @WebMethod
    @ResponseWrapper(localName = "getThingServiceDataResponse", targetNamespace = "http://api.servicemanager.service.betaas.eu/", className = "eu.betaas.apps.lib.soap.GetThingServiceDataResponse")
    public java.lang.String getThingServiceData(
        @WebParam(name = "arg0", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://api.servicemanager.service.betaas.eu/")
        java.lang.String arg2
    );
}
