/*
Copyright 2014-2015 Intecs Spa

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/


/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package eu.betaas.apps.lib.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-10-13T16:50:23.638+02:00
 * Generated source version: 2.7.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "ServiceManagerExternalIF",
                      portName = "ServiceManagerExternalIFPort",
                      targetNamespace = "http://api.servicemanager.service.betaas.eu/",
                      wsdlLocation = "file:/C:/Users/nicola/AppData/Local/Temp/tempdir8190522562031065842.tmp/sm-service_1.wsdl",
                      endpointInterface = "eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType")
                      
public class ServiceManagerExternalIFPortTypeImpl implements ServiceManagerExternalIFPortType {

    private static final Logger LOG = Logger.getLogger(ServiceManagerExternalIFPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#setThingServiceData(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public boolean setThingServiceData(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation setThingServiceData");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#unregister(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public boolean unregister(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation unregister");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#getExtendedServiceData(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public java.lang.String getExtendedServiceData(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation getExtendedServiceData");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#uninstallApplication(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public boolean uninstallApplication(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation uninstallApplication");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#register(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public boolean register(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation register");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#getTaskData(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String getTaskData(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getTaskData");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#installApplication(java.lang.String  arg0 )*
     */
    public java.lang.String installApplication(java.lang.String arg0) { 
        LOG.info("Executing operation installApplication");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#getApplicationServices(java.lang.String  arg0 )*
     */
    public java.lang.String getApplicationServices(java.lang.String arg0) { 
        LOG.info("Executing operation getApplicationServices");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#getGWId(*
     */
    public java.lang.String getGWId() { 
        LOG.info("Executing operation getGWId");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.betaas.apps.lib.soap.ServiceManagerExternalIFPortType#getThingServiceData(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public java.lang.String getThingServiceData(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation getThingServiceData");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
