/**
* Copyright 2014-2015 Converge ICT
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*/

package eu.betaas.adaptation.thingsadaptor.config;

import java.io.Serializable;

/**
 * This class is the Thing Value Object that is used for gathering info for
 * Things and providing them to this and other upper layers 
 * @author Converge
 */
public class Thing implements Serializable {

	
	/**
	 * Autogenerated serial version UID
	 */
	private static final long serialVersionUID = -2080621909261440330L;
	private long id;
	private String name;
	private boolean hasContext;
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isHasContext() {
		return hasContext;
	}
	public void setHasContext(boolean hasContext) {
		this.hasContext = hasContext;
	}

}
