//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.08 at 05:41:25 PM CEST 
//


package eu.betaas.taas.taasvmmanager.occi.datamodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for compute_state.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="compute_state">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INIT"/>
 *     &lt;enumeration value="PENDING"/>
 *     &lt;enumeration value="HOLD"/>
 *     &lt;enumeration value="SUSPENDED"/>
 *     &lt;enumeration value="RESUME"/>
 *     &lt;enumeration value="REBOOT"/>
 *     &lt;enumeration value="RESET"/>
 *     &lt;enumeration value="ACTIVE"/>
 *     &lt;enumeration value="STOPPED"/>
 *     &lt;enumeration value="CANCEL"/>
 *     &lt;enumeration value="SHUTDOWN"/>
 *     &lt;enumeration value="DONE"/>
 *     &lt;enumeration value="FAILED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "compute_state")
@XmlEnum
public enum ComputeState {

    INIT,
    PENDING,
    HOLD,
    SUSPENDED,
    RESUME,
    REBOOT,
    RESET,
    ACTIVE,
    STOPPED,
    CANCEL,
    SHUTDOWN,
    DONE,
    FAILED;

    public String value() {
        return name();
    }

    public static ComputeState fromValue(String v) {
        return valueOf(v);
    }

}
