//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.08 at 05:41:25 PM CEST 
//


package eu.betaas.taas.taasvmmanager.occi.datamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}resource">
 *       &lt;sequence>
 *         &lt;element name="group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quota">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cpu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="memory" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="num_vms" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="storage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="usage">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cpu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="memory" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="num_vms" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="storage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "group",
    "quota",
    "usage"
})
@XmlRootElement(name = "user")
public class User
    extends Resource
{

    @XmlElement(required = true)
    protected String group;
    @XmlElement(required = true)
    protected User.Quota quota;
    @XmlElement(required = true)
    protected User.Usage usage;

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the quota property.
     * 
     * @return
     *     possible object is
     *     {@link User.Quota }
     *     
     */
    public User.Quota getQuota() {
        return quota;
    }

    /**
     * Sets the value of the quota property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.Quota }
     *     
     */
    public void setQuota(User.Quota value) {
        this.quota = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link User.Usage }
     *     
     */
    public User.Usage getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.Usage }
     *     
     */
    public void setUsage(User.Usage value) {
        this.usage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cpu" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="memory" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="num_vms" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="storage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cpu",
        "memory",
        "numVms",
        "storage"
    })
    public static class Quota {

        protected int cpu;
        protected int memory;
        @XmlElement(name = "num_vms")
        protected int numVms;
        protected int storage;

        /**
         * Gets the value of the cpu property.
         * 
         */
        public int getCpu() {
            return cpu;
        }

        /**
         * Sets the value of the cpu property.
         * 
         */
        public void setCpu(int value) {
            this.cpu = value;
        }

        /**
         * Gets the value of the memory property.
         * 
         */
        public int getMemory() {
            return memory;
        }

        /**
         * Sets the value of the memory property.
         * 
         */
        public void setMemory(int value) {
            this.memory = value;
        }

        /**
         * Gets the value of the numVms property.
         * 
         */
        public int getNumVms() {
            return numVms;
        }

        /**
         * Sets the value of the numVms property.
         * 
         */
        public void setNumVms(int value) {
            this.numVms = value;
        }

        /**
         * Gets the value of the storage property.
         * 
         */
        public int getStorage() {
            return storage;
        }

        /**
         * Sets the value of the storage property.
         * 
         */
        public void setStorage(int value) {
            this.storage = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cpu" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="memory" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="num_vms" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="storage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cpu",
        "memory",
        "numVms",
        "storage"
    })
    public static class Usage {

        protected int cpu;
        protected int memory;
        @XmlElement(name = "num_vms")
        protected int numVms;
        protected int storage;

        /**
         * Gets the value of the cpu property.
         * 
         */
        public int getCpu() {
            return cpu;
        }

        /**
         * Sets the value of the cpu property.
         * 
         */
        public void setCpu(int value) {
            this.cpu = value;
        }

        /**
         * Gets the value of the memory property.
         * 
         */
        public int getMemory() {
            return memory;
        }

        /**
         * Sets the value of the memory property.
         * 
         */
        public void setMemory(int value) {
            this.memory = value;
        }

        /**
         * Gets the value of the numVms property.
         * 
         */
        public int getNumVms() {
            return numVms;
        }

        /**
         * Sets the value of the numVms property.
         * 
         */
        public void setNumVms(int value) {
            this.numVms = value;
        }

        /**
         * Gets the value of the storage property.
         * 
         */
        public int getStorage() {
            return storage;
        }

        /**
         * Sets the value of the storage property.
         * 
         */
        public void setStorage(int value) {
            this.storage = value;
        }

    }

}
